"use client";

import { useMemo, useState } from "react";
import { Archive, Braces, FileKey2, KeyRound, LockKeyhole, NotebookText, ShieldAlert, Trash2, X } from "lucide-react";
import { adminRequest, formatDate, useAdminData, useClampedPage } from "@/components/admin/client";
import { ConfirmDialog, EmptyState, ErrorState, LoadingState, PageHeader, Pagination, SearchField, StatusBadge } from "@/components/admin/AdminUI";

type ContentItem = { id: string; title: string; kind: string; status: string; teamId: string; teamName: string; identifier: string | null; language: string | null; creatorName: string | null; shareCount: number; expiresAt: string | null; createdAt: string; updatedAt: string };
type ListData = { items: ContentItem[]; total: number; page: number; pageSize: number; totalPages: number; counts?: Record<string, number> };
const kinds: Record<string, { label: string; icon: typeof KeyRound }> = { totp: { label: "动态验证码", icon: KeyRound }, code: { label: "一次性验证码", icon: FileKey2 }, snippet: { label: "代码片段", icon: Braces }, secret: { label: "临时密文", icon: LockKeyhole }, note: { label: "团队备注", icon: NotebookText } };

export default function ContentPage() {
  const [query, setQuery] = useState(""); const [kind, setKind] = useState("all"); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1);
  const [action, setAction] = useState<{ item: ContentItem; type: "disable" | "restore" | "delete" } | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const url = useMemo(() => `/api/admin/items?q=${encodeURIComponent(query)}&kind=${kind}&status=${status}&page=${page}&pageSize=20`, [query, kind, status, page]);
  const { data, error, loading, reload } = useAdminData<ListData>(url);
  useClampedPage(data, setPage);
  async function performAction() { if (!action) return; setBusy(true); try { if (action.type === "delete") await adminRequest(`/api/admin/items/${action.item.id}`, { method: "DELETE" }); else await adminRequest(`/api/admin/items/${action.item.id}`, { method: "PATCH", body: JSON.stringify({ status: action.type === "restore" ? "active" : "disabled", reason: "运营后台内容治理" }) }); setNotice(action.type === "delete" ? "内容及关联分享已永久删除" : action.type === "restore" ? "内容已恢复" : "内容已停用"); setAction(null); reload(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } }
  return <>
    <PageHeader eyebrow="CONTENT GOVERNANCE" title="内容治理" description="管理内容元数据、有效状态和到期情况；运营人员无法查看正文或密钥。" />
    {notice && <div className="admin-notice" role="status"><span>{notice}</span><button type="button" onClick={() => setNotice("")}><X size={14} /></button></div>}
      <section className="admin-card admin-resource-card"><div className="admin-toolbar multi"><SearchField value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="搜索标题、标识或团队" /><label className="admin-select-label"><span>内容类型</span><select value={kind} onChange={(event) => { setKind(event.target.value); setPage(1); }}><option value="all">全部类型</option>{Object.entries(kinds).map(([value, meta]) => <option value={value} key={value}>{meta.label}</option>)}</select></label><label className="admin-select-label"><span>状态</span><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="all">全部状态</option><option value="active">可用</option><option value="disabled">已停用</option><option value="unavailable">团队不可用</option><option value="expired">已过期</option></select></label><span className="admin-result-count">共 {data?.total || 0} 项</span></div>
      {loading ? <LoadingState label="正在加载内容元数据" /> : error || !data ? <ErrorState message={error} onRetry={reload} /> : !data.items.length ? <EmptyState title={query ? "没有匹配内容" : "内容池还是空的"} description={query ? "请调整搜索词或筛选条件。" : "团队成员通过小程序保存代码、验证码或密文后会显示在这里。"} /> : <><div className="admin-table-wrap"><table className="admin-table resource"><thead><tr><th>内容</th><th>所属团队</th><th>创建者</th><th>分享</th><th>更新时间</th><th>状态</th><th>治理操作</th></tr></thead><tbody>{data.items.map((item) => { const meta = kinds[item.kind] || kinds.note; const Icon = meta.icon; return <tr key={item.id}><td><div className="admin-entity"><span className={`admin-kind-icon ${item.kind}`}><Icon size={16} /></span><span><b>{item.title}</b><small>{meta.label}{item.identifier ? ` · ${item.identifier}` : ""}{item.language ? ` · ${item.language}` : ""}</small></span></div></td><td>{item.teamName}</td><td>{item.creatorName || "已注销用户"}</td><td>{item.shareCount || 0} 次</td><td>{formatDate(item.updatedAt)}</td><td><StatusBadge status={item.status} label={item.status === "active" ? "可用" : undefined} /></td><td><div className="admin-row-actions">{item.status === "active" ? <button type="button" onClick={() => setAction({ item, type: "disable" })}><Archive size={14} />停用</button> : item.status === "disabled" ? <button type="button" onClick={() => setAction({ item, type: "restore" })}>恢复</button> : null}<button className="danger" type="button" onClick={() => setAction({ item, type: "delete" })}><Trash2 size={14} />删除</button></div></td></tr>; })}</tbody></table></div><Pagination page={data.page} totalPages={data.totalPages} onChange={setPage} /></>}
    </section>
    <section className="admin-info-banner warning"><ShieldAlert size={18} /><div><b>高风险操作边界</b><p>永久删除会同时清理关联分享且不可恢复；停用只阻止访问并保留加密数据。所有治理操作都会进入安全审计。</p></div></section>
    <ConfirmDialog open={Boolean(action)} title={action?.type === "delete" ? "永久删除这项内容？" : action?.type === "restore" ? "恢复这项内容？" : "停用这项内容？"} description={action?.type === "delete" ? `“${action.item.title}”的加密正文、元数据及关联分享都会被永久删除，无法恢复。` : action?.type === "restore" ? "恢复后，具备权限的团队成员可以重新访问。" : "停用后团队成员无法继续访问，但数据仍会加密保留。"} confirmLabel={action?.type === "delete" ? "永久删除" : action?.type === "restore" ? "确认恢复" : "确认停用"} danger={action?.type !== "restore"} busy={busy} onCancel={() => setAction(null)} onConfirm={performAction} />
  </>;
}
