"use client";

import { useMemo, useRef, useState } from "react";
import { Ban, ChevronRight, Clock3, RotateCcw, ShieldCheck, UserRoundCheck, Users, X } from "lucide-react";
import { adminRequest, formatDate, useAdminData, useClampedPage } from "@/components/admin/client";
import { ConfirmDialog, EmptyState, ErrorState, LoadingState, PageHeader, Pagination, SearchField, StatusBadge } from "@/components/admin/AdminUI";

type User = { id: string; nickname: string; avatarUrl: string | null; status: string; teamCount: number; ownedTeamCount: number; itemCount: number; createdAt: string; lastLoginAt: string; deletionRequestStatus?: string | null };
type ListData = { items: User[]; total: number; page: number; pageSize: number; totalPages: number; counts?: { active: number; disabled: number } };
type UserDetail = { user: User & { disabledAt?: string | null; disabledReason?: string | null }; teams: Array<{ id: string; name: string; role: string; status: string; joinedAt: string }>; recentAudit: Array<{ id: string; action: string; teamName: string | null; createdAt: string }>; deletionRequests: Array<{ id: string; status: string }> };

function isDeletedUser(user: User, detail?: UserDetail | null) {
  return user.deletionRequestStatus === "completed" || Boolean(detail?.deletionRequests.some((request) => request.status === "completed"));
}

export default function UsersPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1);
  const [confirm, setConfirm] = useState<User | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<User | null>(null); const [detail, setDetail] = useState<UserDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const detailRequest = useRef(0);
  const url = useMemo(() => `/api/admin/users?q=${encodeURIComponent(query)}&status=${status}&page=${page}&pageSize=20`, [query, status, page]);
  const { data, error, loading, reload } = useAdminData<ListData>(url);
  useClampedPage(data, setPage);
  async function openUser(user: User) { const requestId = ++detailRequest.current; setSelected(user); setDetail(null); setDetailLoading(true); try { const result = await adminRequest<UserDetail>(`/api/admin/users/${user.id}`); if (detailRequest.current === requestId) setDetail(result); } catch (reason) { if (detailRequest.current === requestId) setNotice(reason instanceof Error ? reason.message : "用户详情加载失败"); } finally { if (detailRequest.current === requestId) setDetailLoading(false); } }
  async function toggleStatus() { if (!confirm || isDeletedUser(confirm)) return; setBusy(true); const next = confirm.status === "active" ? "disabled" : "active"; try { await adminRequest(`/api/admin/users/${confirm.id}`, { method: "PATCH", body: JSON.stringify({ status: next, reason: "运营后台人工调整" }) }); setNotice(`“${confirm.nickname}”已${next === "active" ? "恢复" : "停用"}`); setConfirm(null); reload(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } }
  return <>
    <PageHeader eyebrow="MEMBERS" title="用户管理" description="查看微信成员活跃状态，并对异常账号进行停用或恢复。" />
    {notice && <div className="admin-notice" role="status"><span>{notice}</span><button type="button" onClick={() => setNotice("")}><X size={14} /></button></div>}
    <section className="admin-mini-metrics"><article><span><Users size={17} /></span><div><small>累计用户</small><strong>{data?.total || 0}</strong></div></article><article><span><UserRoundCheck size={17} /></span><div><small>正常用户</small><strong>{data?.counts?.active ?? data?.items.filter((item) => item.status === "active").length ?? 0}</strong></div></article><article><span><Ban size={17} /></span><div><small>停用 / 注销</small><strong>{data?.counts?.disabled ?? data?.items.filter((item) => item.status === "disabled").length ?? 0}</strong></div></article></section>
    <section className="admin-card admin-resource-card"><div className="admin-toolbar"><SearchField value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="搜索用户昵称" /><div className="admin-segmented">{[["all","全部"],["active","正常"],["disabled","已停用"]].map(([value,label]) => <button type="button" className={status === value ? "selected" : ""} onClick={() => { setStatus(value); setPage(1); }} key={value}>{label}</button>)}</div><span className="admin-result-count">不展示 OpenID 等身份凭据</span></div>
      {loading ? <LoadingState label="正在加载用户" /> : error || !data ? <ErrorState message={error} onRetry={reload} /> : !data.items.length ? <EmptyState title={query ? "没有匹配用户" : "还没有用户"} description={query ? "请尝试其他昵称。" : "用户首次通过微信小程序登录后，会自动出现在这里。"} /> : <><div className="admin-table-wrap"><table className="admin-table resource"><thead><tr><th>用户</th><th>加入团队</th><th>创建内容</th><th>注册时间</th><th>最近登录</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.items.map((user) => { const deleted = isDeletedUser(user); return <tr key={user.id}><td><button className="admin-entity" type="button" onClick={() => openUser(user)}><span className="admin-user-avatar">{user.nickname.slice(0,1)}</span><span><b>{user.nickname}</b><small>{user.ownedTeamCount ? `${user.ownedTeamCount} 个团队的所有者` : "普通成员"}</small></span></button></td><td>{user.teamCount} 个</td><td>{user.itemCount} 项</td><td>{formatDate(user.createdAt, false)}</td><td>{formatDate(user.lastLoginAt)}</td><td><StatusBadge status={deleted ? "deleted" : user.status} label={deleted ? "已注销" : undefined} /></td><td><div className="admin-row-actions"><button type="button" onClick={() => openUser(user)}><ChevronRight size={14} />详情</button>{deleted ? <span>不可恢复</span> : <button className={user.status === "active" ? "danger" : ""} type="button" onClick={() => setConfirm(user)}>{user.status === "active" ? <><Ban size={14} />停用</> : <><RotateCcw size={14} />恢复</>}</button>}</div></td></tr>; })}</tbody></table></div><Pagination page={data.page} totalPages={data.totalPages} onChange={setPage} /></>}
    </section>
    <section className="admin-info-banner"><ShieldCheck size={18} /><div><b>用户隐私保护</b><p>运营后台只展示业务昵称和统计信息，不会返回微信 OpenID、UnionID、登录令牌或敏感内容。</p></div></section>
    {selected && <div className="admin-drawer-layer" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) { detailRequest.current += 1; setSelected(null); setDetail(null); } }}><aside className="admin-drawer" aria-label={`${selected.nickname} 用户详情`}><header><div><span className="admin-user-avatar">{selected.nickname.slice(0,1)}</span><div><small>用户详情</small><h2>{selected.nickname}</h2></div></div><button type="button" onClick={() => { detailRequest.current += 1; setSelected(null); setDetail(null); }} aria-label="关闭"><X size={19} /></button></header>{detailLoading ? <LoadingState label="加载用户详情" /> : detail ? <div className="admin-drawer-body"><section className="admin-detail-summary"><div><span>账号状态</span><StatusBadge status={isDeletedUser(selected, detail) ? "deleted" : detail.user.status} label={isDeletedUser(selected, detail) ? "已注销" : undefined} /></div><div><span>最近登录</span><b>{formatDate(detail.user.lastLoginAt)}</b></div><div><span>加入团队</span><b>{detail.user.teamCount} 个</b></div><div><span>创建内容</span><b>{detail.user.itemCount} 项</b></div></section><section><div className="admin-section-title"><h3>团队与角色</h3><span>{detail.teams.length} 个</span></div><div className="admin-member-list">{detail.teams.map((team) => <div key={team.id}><span className="admin-team-avatar">{team.name.slice(0,1)}</span><span><b>{team.name}</b><small>加入于 {formatDate(team.joinedAt, false)}</small></span><span className={`admin-role ${team.role}`}>{team.role}</span></div>)}</div></section><section><div className="admin-section-title"><h3>最近活动</h3><span>最多 20 条</span></div><div className="admin-compact-log">{detail.recentAudit.length ? detail.recentAudit.map((log) => <div key={log.id}><span><i />{log.action}</span><small><Clock3 size={11} />{formatDate(log.createdAt)}</small></div>) : <p>暂无活动记录</p>}</div></section><section><div className="admin-section-title"><h3>账号控制</h3><span>{isDeletedUser(selected, detail) ? "账号身份已匿名化" : "旧会话会立即失效"}</span></div>{isDeletedUser(selected, detail) ? <p>已完成注销的账号不可恢复；用户可重新注册新账号。</p> : <button className={`admin-button ${detail.user.status === "active" ? "danger" : "secondary"}`} type="button" onClick={() => { detailRequest.current += 1; setConfirm(detail.user); setSelected(null); }}>{detail.user.status === "active" ? <><Ban size={15} />停用并退出所有设备</> : <><RotateCcw size={15} />恢复用户访问</>}</button>}</section></div> : <ErrorState message="用户详情不可用" onRetry={() => openUser(selected)} />}</aside></div>}
    <ConfirmDialog open={Boolean(confirm)} title={confirm?.status === "active" ? "停用这个用户？" : "恢复这个用户？"} description={confirm?.status === "active" ? "停用后用户会立即失去所有团队和内容访问权限，但其历史数据与审计记录会保留。" : "恢复后用户可以重新登录并访问仍有效的团队。"} confirmLabel={confirm?.status === "active" ? "确认停用" : "确认恢复"} danger={confirm?.status === "active"} busy={busy} onCancel={() => setConfirm(null)} onConfirm={toggleStatus} />
  </>;
}
