"use client";

import { useMemo, useState, type FormEvent } from "react";
import { CheckCircle2, CircleAlert, FileCheck2, ShieldAlert, UserRoundX, X } from "lucide-react";
import { adminRequest, formatDate, useAdminData, useClampedPage } from "@/components/admin/client";
import { EmptyState, ErrorState, LoadingState, PageHeader, Pagination, SearchField, StatusBadge } from "@/components/admin/AdminUI";

type DeletionRequest = { id: string; userId: string; nickname: string; userStatus: string; status: "pending" | "approved" | "rejected" | "completed" | "cancelled"; requestedAt: string; processedAt: string | null; requestNote: string | null; processorNote: string | null; ownedTeamCount?: number; activeOwnedTeamCount?: number; blockingOwnedTeamCount?: number };
type ListData = { items: DeletionRequest[]; total: number; page: number; pageSize: number; totalPages: number; counts?: Record<string, number> };
type Decision = { request: DeletionRequest; status: "approved" | "rejected" | "completed" };

export default function DeletionsPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("pending"); const [page, setPage] = useState(1);
  const [decision, setDecision] = useState<Decision | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const url = useMemo(() => `/api/admin/deletion-requests?q=${encodeURIComponent(query)}&status=${status}&page=${page}&pageSize=20`, [query, status, page]);
  const { data, error, loading, reload } = useAdminData<ListData>(url);
  useClampedPage(data, setPage);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!decision) return; const form = new FormData(event.currentTarget); setBusy(true); try { await adminRequest(`/api/admin/deletion-requests/${decision.request.id}`, { method: "PATCH", body: JSON.stringify({ status: decision.status, note: form.get("note") }) }); setNotice(decision.status === "completed" ? "账号已完成匿名化注销" : decision.status === "approved" ? "注销申请已批准" : "注销申请已驳回"); setDecision(null); reload(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "处理失败"); } finally { setBusy(false); } }
  return <>
    <PageHeader eyebrow="PRIVACY REQUESTS" title="注销申请" description="处理用户的数据权利请求；完成注销会撤销会话并最小化身份信息。" />
    {notice && <div className="admin-notice" role="status"><span>{notice}</span><button type="button" onClick={() => setNotice("")}><X size={14} /></button></div>}
    <section className="admin-mini-metrics"><article><span><CircleAlert size={17} /></span><div><small>待处理</small><strong>{data?.counts?.pending || 0}</strong></div></article><article><span><FileCheck2 size={17} /></span><div><small>已批准</small><strong>{data?.counts?.approved || 0}</strong></div></article><article><span><UserRoundX size={17} /></span><div><small>已完成</small><strong>{data?.counts?.completed || 0}</strong></div></article></section>
    <section className="admin-card admin-resource-card"><div className="admin-toolbar"><SearchField value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="搜索用户昵称" /><div className="admin-segmented">{[["all","全部"],["pending","待处理"],["approved","已批准"],["rejected","已驳回"],["completed","已完成"]].map(([value,label]) => <button type="button" className={status === value ? "selected" : ""} onClick={() => { setStatus(value); setPage(1); }} key={value}>{label}</button>)}</div><span className="admin-result-count">共 {data?.total || 0} 条</span></div>
      {loading ? <LoadingState label="正在加载注销申请" /> : error || !data ? <ErrorState message={error} onRetry={reload} /> : !data.items.length ? <EmptyState title="没有待处理申请" description="用户从小程序提交注销申请后会出现在这里。" /> : <><div className="admin-table-wrap"><table className="admin-table resource"><thead><tr><th>申请用户</th><th>申请时间</th><th>拥有团队</th><th>处理时间</th><th>状态</th><th>运营操作</th></tr></thead><tbody>{data.items.map((item) => { const ownedTeams = item.ownedTeamCount ?? 0; const blockingTeams = item.blockingOwnedTeamCount ?? item.activeOwnedTeamCount ?? 0; return <tr key={item.id}><td><div className="admin-entity"><span className="admin-user-avatar">{item.nickname.slice(0,1)}</span><span><b>{item.nickname}</b><small>{item.requestNote ? `用户说明：${item.requestNote}` : `用户状态：${item.userStatus}`}</small></span></div></td><td>{formatDate(item.requestedAt)}</td><td>{ownedTeams} 个团队<small>{blockingTeams > 0 ? `（${blockingTeams} 个需转移）` : ownedTeams > 0 ? "（个人团队将自动停用）" : ""}</small></td><td>{formatDate(item.processedAt)}</td><td><StatusBadge status={item.status} label={{ pending:"待处理", approved:"已批准", rejected:"已驳回", completed:"已完成", cancelled:"已撤回" }[item.status]} /></td><td><div className="admin-row-actions">{item.status === "pending" && <><button type="button" onClick={() => setDecision({ request: item, status: "approved" })}>批准</button><button className="danger" type="button" onClick={() => setDecision({ request: item, status: "rejected" })}>驳回</button></>}{item.status === "approved" && <><button className="danger" type="button" disabled={blockingTeams > 0} title={blockingTeams > 0 ? "请先转移有其他成员的团队所有权" : undefined} onClick={() => setDecision({ request: item, status: "completed" })}>完成注销</button><button type="button" onClick={() => setDecision({ request: item, status: "rejected" })}>终止申请</button></>}{!(["pending","approved"].includes(item.status)) && "—"}</div></td></tr>; })}</tbody></table></div><Pagination page={data.page} totalPages={data.totalPages} onChange={setPage} /></>}
    </section>
    <section className="admin-info-banner warning"><ShieldAlert size={18} /><div><b>完成注销不可逆</b><p>仍有其他有效成员的正常团队必须先转移所有权；仅有申请人的个人团队会自动停用。完成后微信身份信息会匿名化，但团队业务内容和脱敏审计会依法保留。</p></div></section>
    {decision && <div className="admin-modal-layer"><form className="admin-modal admin-form-modal" onSubmit={submit}><span className={`admin-modal-icon${decision.status === "completed" || decision.status === "rejected" ? " danger" : ""}`}>{decision.status === "approved" ? <CheckCircle2 size={22} /> : <ShieldAlert size={22} />}</span><h2>{decision.status === "approved" ? "批准注销申请" : decision.status === "rejected" ? "驳回注销申请" : "完成账号注销"}</h2><p>{decision.status === "completed" ? "这会停用其个人团队、撤销所有会话并匿名化用户身份，操作不可撤销。" : "请填写处理说明，用户可在小程序查看处理状态。"}</p>{decision.request.requestNote && <p><strong>用户提交说明：</strong>{decision.request.requestNote}</p>}<label>处理说明<textarea name="note" maxLength={500} required placeholder={decision.status === "rejected" ? "说明无法处理的原因" : "记录核验和处理依据"} /></label><div><button type="button" className="admin-button secondary" onClick={() => setDecision(null)} disabled={busy}>取消</button><button type="submit" className={`admin-button ${decision.status === "approved" ? "primary" : "danger"}`} disabled={busy}>{busy ? "处理中…" : "确认提交"}</button></div></form></div>}
  </>;
}
